import type { Metadata } from "next";

import { LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms and conditions that govern your use of AIRLY TOOLS.",
};

const sections: LegalSection[] = [
  {
    heading: "Acceptance of terms",
    paragraphs: [
      "By accessing or using AIRLY TOOLS, the AI search service operated by Airly Tools Inc. (referred to as AIRLY TOOLS, we, us or our), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must not use the service. If you are using AIRLY TOOLS on behalf of an organization, you represent that you have the authority to bind that organization to these terms.",
    ],
  },
  {
    heading: "Description of the service",
    paragraphs: [
      "AIRLY TOOLS provides an AI powered search engine that processes natural language queries and returns synthesized answers together with citations to original sources. The service is available through our website, mobile applications and browser extensions. We may add, change or remove features at any time as the product evolves.",
    ],
  },
  {
    heading: "Accounts and eligibility",
    paragraphs: [
      "You must be at least 16 years old to create an account. When you register, you agree to provide accurate information and to keep it up to date. You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Notify us immediately at support@airly.tools if you suspect unauthorized use of your account.",
    ],
  },
  {
    heading: "Acceptable use",
    paragraphs: [
      "You agree to use AIRLY TOOLS only for lawful purposes. In particular, you agree not to:",
    ],
    list: [
      "Use the service to violate any applicable law or regulation.",
      "Attempt to probe, scan or test the vulnerability of our systems or circumvent any security measures.",
      "Use automated scripts, bots or scrapers to access the service beyond the limits of your plan or our published API terms.",
      "Resell, sublicense or redistribute the service or its output without our written permission.",
      "Use the service to generate or spread content that is unlawful, defamatory, harassing or deceptive.",
      "Interfere with or disrupt the integrity or performance of the service for other users.",
    ],
  },
  {
    heading: "Subscriptions and payments",
    paragraphs: [
      "Paid plans are billed in advance on a monthly or yearly basis and renew automatically until cancelled. Prices are displayed before purchase and may change with at least 30 days notice. You can cancel at any time from your account settings; access to paid features continues until the end of the paid period. Within the first 30 days of a new Pro subscription you may request a full refund by contacting support.",
    ],
  },
  {
    heading: "AI generated content",
    paragraphs: [
      "Answers produced by AIRLY TOOLS are generated by artificial intelligence based on third party sources. While we work hard to make answers accurate and always provide citations, we cannot guarantee that every answer is complete, current or correct. Answers are provided for informational purposes only and do not constitute professional, legal, medical or financial advice. Always verify important information using the cited sources or a qualified professional.",
    ],
  },
  {
    heading: "Intellectual property",
    paragraphs: [
      "The service, including its software, design, trademarks and content created by us, is owned by Airly Tools Inc. and protected by intellectual property laws. We grant you a limited, personal, revocable license to use the service in accordance with these terms. Content from third party sources remains the property of its respective owners, and citations link back to those sources.",
    ],
  },
  {
    heading: "Privacy",
    paragraphs: [
      "Your privacy matters to us. Our Privacy Policy explains what data we collect, why we collect it and how you can control it. By using the service you agree to the processing of your information as described in the Privacy Policy.",
    ],
  },
  {
    heading: "Disclaimer of warranties",
    paragraphs: [
      "The service is provided on an as is and as available basis. To the maximum extent permitted by law, we disclaim all warranties, whether express or implied, including warranties of merchantability, fitness for a particular purpose and non infringement. We do not warrant that the service will be uninterrupted, error free or completely secure.",
    ],
  },
  {
    heading: "Limitation of liability",
    paragraphs: [
      "To the maximum extent permitted by law, Airly Tools Inc. shall not be liable for any indirect, incidental, special, consequential or punitive damages, or for any loss of profits, data or goodwill, arising out of or in connection with your use of the service. Our total aggregate liability for any claim arising from these terms or the service shall not exceed the amount you paid us in the twelve months preceding the claim, or one hundred US dollars if you have not paid us anything.",
    ],
  },
  {
    heading: "Termination",
    paragraphs: [
      "You may stop using the service and delete your account at any time. We may suspend or terminate your access if you materially breach these terms, if required by law, or if we discontinue the service. Where reasonable, we will give you notice and an opportunity to export your data before termination takes effect.",
    ],
  },
  {
    heading: "Changes to these terms",
    paragraphs: [
      "We may update these terms from time to time. If the changes are material, we will notify you by email or through the service at least 14 days before they take effect. Your continued use of the service after the effective date constitutes acceptance of the updated terms.",
    ],
  },
  {
    heading: "Governing law",
    paragraphs: [
      "These terms are governed by the laws of the State of California, without regard to its conflict of law principles. Any disputes arising from these terms or the service shall be resolved in the state or federal courts located in San Francisco County, California, and you consent to their jurisdiction.",
    ],
  },
  {
    heading: "Contact",
    paragraphs: [
      "Questions about these terms? Write to us at legal@airly.tools or by post at Airly Tools Inc., 548 Market Street, San Francisco, CA 94104, United States.",
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="June 1, 2026"
      intro="These Terms of Service govern your access to and use of AIRLY TOOLS. Please read them carefully. They describe your rights and responsibilities when using our AI search service."
      sections={sections}
    />
  );
}
